package com.example.readbook.utils;

import android.app.Activity;

import com.example.readbook.MainActivity;
import com.example.readbook.R;
import com.example.readbook.model.Book;
import com.example.readbook.model.BookDetails;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

public class AllListData {
    public ArrayList<Book> getBookData(){
        ArrayList<Book> books = new ArrayList<>();
        books.add(new Book(R.drawable.things_fall_apart, "Things Fall Apart", "209", "Chinua Achebe", new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("23/04/1958 23:11:59")),new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("13/07/1950 23:11:59")), "Funny", "Activity"));
        books.add(new Book(R.drawable.fairy_tales, "Fairy tales", "784", "Hans Christian Andersen", new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("23/04/1836 20:10:00")),new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("13/07/1829 23:11:59")), "Romantic", "Closed"));
        books.add(new Book(R.drawable.the_divine_comedy, "The Divine Comedy", "928", "Dante Alighieri", new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("10/01/1315 20:10:00")),new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("25/07/1310 23:11:59")), "Comedy", "Activity"));
        books.add(new Book(R.drawable.things_fall_apart, "Things Fall Apart", "209", "Chinua Achebe",new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("23/04/1958 23:11:59")),new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("13/07/1950 23:11:59")), "Funny", "Activity"));
        books.add(new Book(R.drawable.fairy_tales, "Fairy tales", "784", "Hans Christian Andersen", new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("23/04/1836 20:10:00")),new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("13/07/1829 23:11:59")), "Romantic", "Closed"));
        books.add(new Book(R.drawable.the_divine_comedy, "The Divine Comedy", "928", "Dante Alighieri", new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("10/01/1315 20:10:00")),new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("25/07/1310 23:11:59")), "Comedy", "Activity"));
        books.add(new Book(R.drawable.things_fall_apart, "Things Fall Apart", "209", "Chinua Achebe", new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("23/04/1958 23:11:59")),new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("13/07/1950 23:11:59")), "Funny", "Activity"));
        books.add(new Book(R.drawable.fairy_tales, "Fairy tales", "784", "Hans Christian Andersen", new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("23/04/1836 20:10:00")),new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("13/07/1829 23:11:59")), "Romantic", "Closed"));
        books.add(new Book(R.drawable.the_divine_comedy, "The Divine Comedy", "928", "Dante Alighieri", new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("10/01/1315 20:10:00")),new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date("25/07/1310 23:11:59")), "Comedy", "Activity"));
        return books;
    }

    public ArrayList<BookDetails> getBookDetailData(){
        ArrayList<BookDetails> bookDetails = new ArrayList<>();
        bookDetails.add(new BookDetails("Things Fall Apart", "Things Fall Apart, first novel by Chinua Achebe, written in English and published in 1958. Things Fall Apart helped create the Nigerian literary renaissance of the 1960s.\n" +
                "ZUMAPRESS.com— Keystone Pictures/age fotostock\n" +
                "Afar. Ethiopia. Cattle move towards Lake Abhebad in Afar, Ethiopia.\n" +
                "BRITANNICA QUIZ\n" +
                "Destination Africa: Fact or Fiction?\n" +
                "All countries with Guinea in their names are in Africa.\n" +
                "The novel chronicles the life of Okonkwo, the leader of an Igbo community, from the events leading up to his banishment from the community for accidentally killing a clansman, through the seven years of his exile, to his return, and it addresses a particular problem of emergent Africa—the intrusion in the 1890s of white missionaries and colonial government into tribal Igbo society. Traditionally structured, and peppered with Igbo proverbs, it describes the simultaneous disintegration of its protagonist Okonkwo and of his village. The novel was praised for its intelligent and realistic treatment of tribal beliefs and of psychological disintegration coincident with social unraveling."));
        bookDetails.add(new BookDetails("Fairy tales", "     Cinderella - Her evil stepmother and stepsisters would not let her go to the ball, but her fairy godmother made it happen with magic. She danced with the prince and they fell in love. Since she had to leave by midnight, she ran and lost one slipper. The prince found the slipper and searched for her. After he found her, they were married and lived happily ever after.\n" +
                "\n" +
                "Elves and the Shoemaker - A shoemaker and his wife were very poor. One day they ran out of leather so they went to bed. In the morning, they found a pair of shoes and a passerby bought them. The next night, another pair of shoes appeared. The third night they hid and saw two elves making shoes. In gratitude, they made clothes for the elves, as winter was approaching. The elves were very happy and went on to help someone else.\n" +
                "\n" +
                "Emperor's New Clothes - A vain emperor hired two people to make him some new clothes. The tricked him, telling him the cloth was not visible to people unfit for his position or who were very stupid. At first the people pretended to see the clothes, but a child says that he is not wearing clothes and people start to agree. The emperor realized he was swindled but continues the parade anyway.\n" +
                "\n" +
                "Frog-Prince - A frog asked a princess why she was crying and she replied that she had dropped her golden ball into the pond. She promised anything if he would get it for her. He did and asked to eat from her plate, live in the castle, and that she be his friend. She did and he turned into a prince as he had been under a spell from a witch. They married and lived happily ever after.\n" +
                "\n" +
                "The Gingerbread Man - A little old woman baked a gingerbread man and when she took him out of the oven, he ran away. The woman and her husband chased him, as well as the pig, cow and horse. No one could catch him. He came to a river and a sly fox told him he could jump on his tail and he would take him across. He did and the fox went deeper and the gingerbread man had to jump on his back and then on his nose. When he got to his nose, the fox ate him.\n" +
                "\n" +
                "Goldilocks and the Three Bears - Goldilocks saw a cabin in the woods and entered, she found three bowls of porridge, one was too cold, one too hot and the other just right, so she ate it. She found three chairs, one to hard, one too soft, and the little one was just right and she sat in it and broke it. Of the three beds, one was too hard, one too soft and one just right, so she fell asleep. The bears came home and frightened her and she ran away.\n" +
                "\n" +
                "Hansel and Gretel - The two childrens' wicked stepmother took them into the forest and left them there. They came upon a house made of sweets and they ate some. The evil witch that lived there locked them in a cage and was going to make a soup out of them. Gretel got out of the cage and pushed the witch into the boiling water. The children found treasure there and took it home and they were never hungry again.\n" +
                "\n" +
                "Jack and the Bean Stalk - Jack took the family cow to sell and traded it for magic beans. His mother was angry and threw them out of the window. The next morning a giant beanstalk had grown. He climbed the beanstalk and found a giant there who had gold coins. Jack stole them and took them home. Later, Jack returned and saw a hen that laid golden eggs and he stole that, too. The third time he tried to steal a magic harp and the harp cried out. The giant chased Jack down the beanstalk, Jack chopped it down and the giant died.\n" +
                "\n" +
                "Little Red Riding Hood - Little Red Riding Hood's mother sent her to Grandma's house with a basket of goodies and told her not to talk to strangers. A wolf asked here where she was going and she told him. He went to Grandma's house, locked Grandma in the cupboard and put on her clothes. Little Red Riding Hood was surprised at Grandma's eyes, ears and teeth, remarking on how big they were. The wolf said the teeth were better for eating and he pounced. She screamed, some woodcutters heard her cry and rescued her.\n" +
                "\n" +
                "The Pied Piper of Hamelin - The town of Hamlyn was overrun with rats. The Pied Piper offered to get rid of the rats for 50 pounds and the mayor agreed. He started playing his pipe. The rats followed him and he led them into the harbor and they died. He went back for his money but the mayor only paid 20 pounds. The Pied Piper wanted to teach him a lesson, so he played his pipe and all the children followed him out of town. The mayor sent men to find the children but they could not find them.\n" +
                "\n" +
                "Pinocchio - Gepetto was a poor carpenter who carved a puppet that became live. He named him Pinocchio and sent him to school. One day Pinocchio joined a puppet show but the puppet master wanted him for firewood. He begged to be spared and told him about his poor father. He was spared and the puppet master gave him five gold coins for his father.\n" +
                "\n" +
                "Princess and the Pea - A prince wanted to make sure he married a real princess. He devised a test for an unexpected guest who claimed she was a princess. He placed a pea beneath 20 mattresses and 20 feather beds thinking only a princess could be sensitive enough to feel the small pea. The next morning, hte princess said she did not sleep because of something hard in her bed. The two were married and lived happily everafter.\n" +
                "\n" +
                "Sleeping Beauty - A princess was born and an old fairy placed a spell that she would prick her finger on a spindle when she was 16 and die. The good fairies made another spell so that she would only sleep for 100 years and a prince would awaken her. When she was 16, the witch, disguised as an old lady, showed her a spinning wheel and she touched the spindle and fell asleep. The good fairies decided to make everyone sleep. After 100 years, a prince from another land found her and kissed her. Everyone awoke, they married and lived happily every after.\n" +
                "\n" +
                "Snow White and the Seven Dwarfs - Snow White's evil stepmother wanted to be the fairest in the land and was jealous of Snow White's beauty. The stepmother ordered Snow White to be killed but the huntsman spared her life. Snow White came upon a cottage that belonged to seven dwarfs and they let her stay. Soon the wicked stepmother found her, disguised herself and took her a poison apple. She fell into a deep sleep and the dwarfs made a crystal coffin for her. Prince Charming came by the cottage, saw her, kissed her, and she awoke. They were married and lived happily ever after.\n" +
                "\n" +
                "Three Little Pigs - One pig built a house of straw and the second a house of sticks, because they were lazy. The third took the time to build a strong house with bricks. When the big bad wolf came, he huffed and puffed and blew the straw and stick houses down. He couldn't blow down the brick house and the pigs put a pot of boiling water in the fireplace. The wolf fell into it and died.\n" +
                "\n" +
                "Thumbelina - A woman wished for a baby, even a tiny one. A fairy granted her wish and gave her a seed to plant. When it bloomed, a tiny baby was inside. A toad fell in love with the baby and kidnapped her. A swallow rescued the baby and took her away to warmer lands. There, Thumbelina found another tiny person just like her. He asked her to marry him and she became queen of the flowers.\n" +
                "\n" +
                "Ugly Ducklibong - One duckling did not look like the others and he was sad. He decided to run away and came across a cottage. He stayed there for a while but the children scared him. He left and spent the winter in the pond. In the spring, he saw his reflection and realized he was a swan."));
        bookDetails.add(new BookDetails("The Divine Comedy", "Dante’s years of exile were years of difficult peregrinations from one place to another—as he himself repeatedly says, most effectively in Paradiso [XVII], in Cacciaguida’s moving lamentation that “bitter is the taste of another man’s bread and…heavy the way up and down another man’s stair.” Throughout his exile Dante nevertheless was sustained by work on his great poem. The Divine Comedy was possibly begun prior to 1308 and completed just before his death in 1321, but the exact dates are uncertain. In addition, in his final years Dante was received honourably in many noble houses in the north of Italy, most notably by Guido Novello da Polenta, the nephew of the remarkable Francesca, in Ravenna. There at his death Dante was given an honourable burial attended by the leading men of letters of the time, and the funeral oration was delivered by Guido himself.\n" +
                "Gabriele D'Annunzio.\n" +
                "READ MORE ON THIS TOPIC\n" +
                "Italian literature: Dante (1265–1321)\n" +
                "Dante Alighieri is one of the most important and influential names in all of European literature, but it was only after...\n" +
                "The plot of The Divine Comedy is simple: a man, generally assumed to be Dante himself, is miraculously enabled to undertake an ultramundane journey, which leads him to visit the souls in Hell, Purgatory, and Paradise. He has two guides: Virgil, who leads him through the Inferno and Purgatorio, and Beatrice, who introduces him to Paradiso. Through these fictional encounters taking place from Good Friday evening in 1300 through Easter Sunday and slightly beyond, Dante learns of the exile that is awaiting him (which had, of course, already occurred at the time of the writing). This device allowed Dante not only to create a story out of his pending exile but also to explain the means by which he came to cope with his personal calamity and to offer suggestions for the resolution of Italy’s troubles as well. Thus, the exile of an individual becomes a microcosm of the problems of a country, and it also becomes representative of the fall of humankind. Dante’s story is thus historically specific as well as paradigmatic.\n" +
                "Dante and Virgil beset by demons, passing through Hell, illustration by Gustave Doré for an 1861 edition of Dante's Inferno (The Divine Comedy).\n" +
                "© Photos.com/Thinkstock\n" +
                "The basic structural component of The Divine Comedy is the canto. The poem consists of 100 cantos, which are grouped together into three sections, or canticles, Inferno, Purgatorio, and Paradiso. Technically there are 33 cantos in each canticle and one additional canto, contained in the Inferno, which serves as an introduction to the entire poem. For the most part the cantos range from about 136 to about 151 lines. The poem’s rhyme scheme is the terza rima (aba, bcb, cdc, etc.). Thus, the divine number of three is present in every part of the work.\n" +
                "Dante’s Inferno differs from its great classical predecessors in both position and purpose. In Homer’s Odyssey (Book XII) and Virgil’s Aeneid (Book VI) the visit to the land of the dead occurs in the middle of the poem because in these centrally placed books the essential values of life are revealed. Dante, while adopting the convention, transforms the practice by beginning his journey with the visit to the land of the dead. He does this because his poem’s spiritual pattern is not classical but Christian: Dante’s journey to Hell represents the spiritual act of dying to the world, and hence it coincides with the season of Christ’s own death. (In this way, Dante’s method is similar to that of Milton in Paradise Lost, where the flamboyant but defective Lucifer and his fallen angels are presented first.) The Inferno represents a false start during which Dante, the character, must be disabused of harmful values that somehow prevent him from rising above his fallen world. Despite the regressive nature of the Inferno, Dante’s meetings with the roster of the damned are among the most memorable moments of the poem: the Neutrals, the virtuous pagans, Francesca da Rimini, Filipo Argenti, Farinata degli Uberti, Piero delle Vigne, Brunetto Latini, the simoniacal popes, Ulysses, and Ugolino della Gherardesca impose themselves upon the reader’s imagination with tremendous force.\n" +
                "The visit to Hell is, as Virgil and later Beatrice explain, an extreme measure, a painful but necessary act before real recovery can begin. This explains why the Inferno is both aesthetically and theologically incomplete. For instance, readers frequently express disappointment at the lack of dramatic or emotional power in the final encounter with Satan in canto XXXIV. But because the journey through the Inferno primarily signifies a process of separation and thus is only the initial step in a fuller development, it must end with a distinct anticlimax. In a way this is inevitable because the final revelation of Satan can have nothing new to offer: the sad effects of his presence in human history have already become apparent throughout the Inferno.\n" +
                "In the Purgatorio the protagonist’s painful process of spiritual rehabilitation commences; in fact, this part of the journey may be considered the poem’s true moral starting point. Here the pilgrim Dante subdues his own personality in order that he may ascend. In fact, in contrast to the Inferno, where Dante is confronted with a system of models that needs to be discarded, in the Purgatorio few characters present themselves as models; all of the penitents are pilgrims along the road of life. Dante, rather than being an awed if alienated observer, is an active participant. If the Inferno is a canticle of enforced and involuntary alienation, in which Dante learns how harmful were his former allegiances, in the Purgatorio he comes to accept as most fitting the essential Christian image of life as a pilgrimage. As Beatrice in her magisterial return in the earthly paradise reminds Dante, he must learn to reject the deceptive promises of the temporal world.\n" +
                "Despite its harsh regime, the Purgatorio is the realm of spiritual dawn, where larger visions are entertained. Whereas in only one canto of the Inferno (VII), in which Fortuna is discussed, is there any suggestion of philosophy, in the Purgatorio, historical, political, and moral vistas are opened up. It is, moreover, the great canticle of poetry and the arts. Dante meant it literally when he proclaimed, after the dreary dimensions of Hell: “But here let poetry rise again from the dead.” There is only one poet in Hell proper and not more than two in the Paradiso, but in the Purgatorio the reader encounters the musicians Casella and Belacqua and the poet Sordello and hears of the fortunes of the two Guidos, Guinizelli and Cavalcanti, the painters Cimabue and Giotto, and the miniaturists. In the upper reaches of Purgatory, the reader observes Dante reconstructing his classical tradition and then comes even closer to Dante’s own great native tradition (placed higher than the classical tradition) when he meets Forese Donati, hears explained—in an encounter with Bonagiunta da Lucca—the true resources of the dolce stil nuovo, and meets with Guido Guinizelli and hears how he surpassed in skill and poetic mastery the reigning regional poet, Guittone d’Arezzo. These cantos resume the line of thought presented in the Inferno (IV), where among the virtuous pagans Dante announces his own program for an epic and takes his place, “sixth among that number,” alongside the classical writers. In the Purgatorio he extends that tradition to include Statius (whose Thebaid did in fact provide the matter for the more grisly features of the lower inferno), but he also shows his more modern tradition originating in Guinizelli. Shortly after his encounter with Guinizelli comes the long-awaited reunion with Beatrice in the earthly paradise. Thus, from the classics Dante seems to have derived his moral and political understanding as well as his conception of the epic poem—that is, a framing story large enough to encompass the most important issues of his day, but it was from his native tradition that he acquired the philosophy of love that forms the Christian matter of his poem.\n" +
                "This means of course that Virgil, Dante’s guide, must give way to other leaders, and in a canticle generally devoid of drama the rejection of Virgil becomes the single dramatic event. Dante’s use of Virgil is one of the richest cultural appropriations in literature. To begin, in Dante’s poem he is an exponent of classical reason. He is also a historical figure and is presented as such in the Inferno (I): “…once I was a man, and my parents were Lombards, both Mantuan by birth. I was born sub Julio, though late in his time, and I lived in Rome under the good Augustus, in the time of the false and lying gods.” Virgil, moreover, is associated with Dante’s homeland (his references are to contemporary Italian places), and his background is entirely imperial. (Born under Julius Caesar, he extolled Augustus Caesar.) He is presented as a poet, the theme of whose great epic sounds remarkably similar to that of Dante’s poem: “I was a poet and sang of that just son of Anchises who came from Troy after proud Ilium was burned.” So, too, Dante sings of the just son of a city, Florence, who was unjustly expelled, and forced to search, as Aeneas had done, for a better city, in his case the heavenly city.\n" +
                "Virgil is a poet whom Dante had studied carefully and from whom he had acquired his poetic style, the beauty of which has brought him much honour. But Dante had lost touch with Virgil in the intervening years, and when the spirit of Virgil returns it is one that seems weak from long silence. But the Virgil that returns is more than a stylist; he is the poet of the Roman Empire, a subject of great importance to Dante, and he is a poet who has become a saggio, a sage, or moral teacher.\n" +
                "Though an exponent of reason, Virgil has become an emissary of divine grace, and his return is part of the revival of those simpler faiths associated with Dante’s earlier trust in Beatrice. And yet, of course, Virgil by himself is insufficient. It cannot be said that Dante rejects Virgil; rather, he sadly found that nowhere in Virgil’s work—that is, in his consciousness—was there any sense of personal liberation from the enthrallment of history and its processes. Virgil had provided Dante with moral instruction in survival as an exile, which is the theme of his own poem as well as Dante’s, but he clung to his faith in the processes of history, which, given their culmination in the Roman Empire, were deeply consoling. Dante, on the other hand, was determined to go beyond history because it had become for him a nightmare.\n" +
                "In the Paradiso true heroic fulfillment is achieved. Dante’s poem gives expression to those figures from the past who seem to defy death. Their historical impact continues and the totality of their commitment inspires in their followers a feeling of exaltation and a desire for identification. In his encounters with such characters as his great-great-grandfather Cacciaguida and Saints Francis, Dominic, and Bernard, Dante is carried beyond himself. The Paradiso is consequently a poem of fulfillment and of completion. It is the fulfillment of what is prefigured in the earlier canticles. Aesthetically it completes the poem’s elaborate system of anticipation and retrospection."));
        bookDetails.add(new BookDetails("Things Fall Apart", "Things Fall Apart, first novel by Chinua Achebe, written in English and published in 1958. Things Fall Apart helped create the Nigerian literary renaissance of the 1960s.\n" +
                "ZUMAPRESS.com— Keystone Pictures/age fotostock\n" +
                "Afar. Ethiopia. Cattle move towards Lake Abhebad in Afar, Ethiopia.\n" +
                "BRITANNICA QUIZ\n" +
                "Destination Africa: Fact or Fiction?\n" +
                "All countries with Guinea in their names are in Africa.\n" +
                "The novel chronicles the life of Okonkwo, the leader of an Igbo community, from the events leading up to his banishment from the community for accidentally killing a clansman, through the seven years of his exile, to his return, and it addresses a particular problem of emergent Africa—the intrusion in the 1890s of white missionaries and colonial government into tribal Igbo society. Traditionally structured, and peppered with Igbo proverbs, it describes the simultaneous disintegration of its protagonist Okonkwo and of his village. The novel was praised for its intelligent and realistic treatment of tribal beliefs and of psychological disintegration coincident with social unraveling."));
        bookDetails.add(new BookDetails("Fairy tales", "     Cinderella - Her evil stepmother and stepsisters would not let her go to the ball, but her fairy godmother made it happen with magic. She danced with the prince and they fell in love. Since she had to leave by midnight, she ran and lost one slipper. The prince found the slipper and searched for her. After he found her, they were married and lived happily ever after.\n" +
                "\n" +
                "Elves and the Shoemaker - A shoemaker and his wife were very poor. One day they ran out of leather so they went to bed. In the morning, they found a pair of shoes and a passerby bought them. The next night, another pair of shoes appeared. The third night they hid and saw two elves making shoes. In gratitude, they made clothes for the elves, as winter was approaching. The elves were very happy and went on to help someone else.\n" +
                "\n" +
                "Emperor's New Clothes - A vain emperor hired two people to make him some new clothes. The tricked him, telling him the cloth was not visible to people unfit for his position or who were very stupid. At first the people pretended to see the clothes, but a child says that he is not wearing clothes and people start to agree. The emperor realized he was swindled but continues the parade anyway.\n" +
                "\n" +
                "Frog-Prince - A frog asked a princess why she was crying and she replied that she had dropped her golden ball into the pond. She promised anything if he would get it for her. He did and asked to eat from her plate, live in the castle, and that she be his friend. She did and he turned into a prince as he had been under a spell from a witch. They married and lived happily ever after.\n" +
                "\n" +
                "The Gingerbread Man - A little old woman baked a gingerbread man and when she took him out of the oven, he ran away. The woman and her husband chased him, as well as the pig, cow and horse. No one could catch him. He came to a river and a sly fox told him he could jump on his tail and he would take him across. He did and the fox went deeper and the gingerbread man had to jump on his back and then on his nose. When he got to his nose, the fox ate him.\n" +
                "\n" +
                "Goldilocks and the Three Bears - Goldilocks saw a cabin in the woods and entered, she found three bowls of porridge, one was too cold, one too hot and the other just right, so she ate it. She found three chairs, one to hard, one too soft, and the little one was just right and she sat in it and broke it. Of the three beds, one was too hard, one too soft and one just right, so she fell asleep. The bears came home and frightened her and she ran away.\n" +
                "\n" +
                "Hansel and Gretel - The two childrens' wicked stepmother took them into the forest and left them there. They came upon a house made of sweets and they ate some. The evil witch that lived there locked them in a cage and was going to make a soup out of them. Gretel got out of the cage and pushed the witch into the boiling water. The children found treasure there and took it home and they were never hungry again.\n" +
                "\n" +
                "Jack and the Bean Stalk - Jack took the family cow to sell and traded it for magic beans. His mother was angry and threw them out of the window. The next morning a giant beanstalk had grown. He climbed the beanstalk and found a giant there who had gold coins. Jack stole them and took them home. Later, Jack returned and saw a hen that laid golden eggs and he stole that, too. The third time he tried to steal a magic harp and the harp cried out. The giant chased Jack down the beanstalk, Jack chopped it down and the giant died.\n" +
                "\n" +
                "Little Red Riding Hood - Little Red Riding Hood's mother sent her to Grandma's house with a basket of goodies and told her not to talk to strangers. A wolf asked here where she was going and she told him. He went to Grandma's house, locked Grandma in the cupboard and put on her clothes. Little Red Riding Hood was surprised at Grandma's eyes, ears and teeth, remarking on how big they were. The wolf said the teeth were better for eating and he pounced. She screamed, some woodcutters heard her cry and rescued her.\n" +
                "\n" +
                "The Pied Piper of Hamelin - The town of Hamlyn was overrun with rats. The Pied Piper offered to get rid of the rats for 50 pounds and the mayor agreed. He started playing his pipe. The rats followed him and he led them into the harbor and they died. He went back for his money but the mayor only paid 20 pounds. The Pied Piper wanted to teach him a lesson, so he played his pipe and all the children followed him out of town. The mayor sent men to find the children but they could not find them.\n" +
                "\n" +
                "Pinocchio - Gepetto was a poor carpenter who carved a puppet that became live. He named him Pinocchio and sent him to school. One day Pinocchio joined a puppet show but the puppet master wanted him for firewood. He begged to be spared and told him about his poor father. He was spared and the puppet master gave him five gold coins for his father.\n" +
                "\n" +
                "Princess and the Pea - A prince wanted to make sure he married a real princess. He devised a test for an unexpected guest who claimed she was a princess. He placed a pea beneath 20 mattresses and 20 feather beds thinking only a princess could be sensitive enough to feel the small pea. The next morning, hte princess said she did not sleep because of something hard in her bed. The two were married and lived happily everafter.\n" +
                "\n" +
                "Sleeping Beauty - A princess was born and an old fairy placed a spell that she would prick her finger on a spindle when she was 16 and die. The good fairies made another spell so that she would only sleep for 100 years and a prince would awaken her. When she was 16, the witch, disguised as an old lady, showed her a spinning wheel and she touched the spindle and fell asleep. The good fairies decided to make everyone sleep. After 100 years, a prince from another land found her and kissed her. Everyone awoke, they married and lived happily every after.\n" +
                "\n" +
                "Snow White and the Seven Dwarfs - Snow White's evil stepmother wanted to be the fairest in the land and was jealous of Snow White's beauty. The stepmother ordered Snow White to be killed but the huntsman spared her life. Snow White came upon a cottage that belonged to seven dwarfs and they let her stay. Soon the wicked stepmother found her, disguised herself and took her a poison apple. She fell into a deep sleep and the dwarfs made a crystal coffin for her. Prince Charming came by the cottage, saw her, kissed her, and she awoke. They were married and lived happily ever after.\n" +
                "\n" +
                "Three Little Pigs - One pig built a house of straw and the second a house of sticks, because they were lazy. The third took the time to build a strong house with bricks. When the big bad wolf came, he huffed and puffed and blew the straw and stick houses down. He couldn't blow down the brick house and the pigs put a pot of boiling water in the fireplace. The wolf fell into it and died.\n" +
                "\n" +
                "Thumbelina - A woman wished for a baby, even a tiny one. A fairy granted her wish and gave her a seed to plant. When it bloomed, a tiny baby was inside. A toad fell in love with the baby and kidnapped her. A swallow rescued the baby and took her away to warmer lands. There, Thumbelina found another tiny person just like her. He asked her to marry him and she became queen of the flowers.\n" +
                "\n" +
                "Ugly Ducklibong - One duckling did not look like the others and he was sad. He decided to run away and came across a cottage. He stayed there for a while but the children scared him. He left and spent the winter in the pond. In the spring, he saw his reflection and realized he was a swan."));
        bookDetails.add(new BookDetails("The Divine Comedy", "Dante’s years of exile were years of difficult peregrinations from one place to another—as he himself repeatedly says, most effectively in Paradiso [XVII], in Cacciaguida’s moving lamentation that “bitter is the taste of another man’s bread and…heavy the way up and down another man’s stair.” Throughout his exile Dante nevertheless was sustained by work on his great poem. The Divine Comedy was possibly begun prior to 1308 and completed just before his death in 1321, but the exact dates are uncertain. In addition, in his final years Dante was received honourably in many noble houses in the north of Italy, most notably by Guido Novello da Polenta, the nephew of the remarkable Francesca, in Ravenna. There at his death Dante was given an honourable burial attended by the leading men of letters of the time, and the funeral oration was delivered by Guido himself.\n" +
                "Gabriele D'Annunzio.\n" +
                "READ MORE ON THIS TOPIC\n" +
                "Italian literature: Dante (1265–1321)\n" +
                "Dante Alighieri is one of the most important and influential names in all of European literature, but it was only after...\n" +
                "The plot of The Divine Comedy is simple: a man, generally assumed to be Dante himself, is miraculously enabled to undertake an ultramundane journey, which leads him to visit the souls in Hell, Purgatory, and Paradise. He has two guides: Virgil, who leads him through the Inferno and Purgatorio, and Beatrice, who introduces him to Paradiso. Through these fictional encounters taking place from Good Friday evening in 1300 through Easter Sunday and slightly beyond, Dante learns of the exile that is awaiting him (which had, of course, already occurred at the time of the writing). This device allowed Dante not only to create a story out of his pending exile but also to explain the means by which he came to cope with his personal calamity and to offer suggestions for the resolution of Italy’s troubles as well. Thus, the exile of an individual becomes a microcosm of the problems of a country, and it also becomes representative of the fall of humankind. Dante’s story is thus historically specific as well as paradigmatic.\n" +
                "Dante and Virgil beset by demons, passing through Hell, illustration by Gustave Doré for an 1861 edition of Dante's Inferno (The Divine Comedy).\n" +
                "© Photos.com/Thinkstock\n" +
                "The basic structural component of The Divine Comedy is the canto. The poem consists of 100 cantos, which are grouped together into three sections, or canticles, Inferno, Purgatorio, and Paradiso. Technically there are 33 cantos in each canticle and one additional canto, contained in the Inferno, which serves as an introduction to the entire poem. For the most part the cantos range from about 136 to about 151 lines. The poem’s rhyme scheme is the terza rima (aba, bcb, cdc, etc.). Thus, the divine number of three is present in every part of the work.\n" +
                "Dante’s Inferno differs from its great classical predecessors in both position and purpose. In Homer’s Odyssey (Book XII) and Virgil’s Aeneid (Book VI) the visit to the land of the dead occurs in the middle of the poem because in these centrally placed books the essential values of life are revealed. Dante, while adopting the convention, transforms the practice by beginning his journey with the visit to the land of the dead. He does this because his poem’s spiritual pattern is not classical but Christian: Dante’s journey to Hell represents the spiritual act of dying to the world, and hence it coincides with the season of Christ’s own death. (In this way, Dante’s method is similar to that of Milton in Paradise Lost, where the flamboyant but defective Lucifer and his fallen angels are presented first.) The Inferno represents a false start during which Dante, the character, must be disabused of harmful values that somehow prevent him from rising above his fallen world. Despite the regressive nature of the Inferno, Dante’s meetings with the roster of the damned are among the most memorable moments of the poem: the Neutrals, the virtuous pagans, Francesca da Rimini, Filipo Argenti, Farinata degli Uberti, Piero delle Vigne, Brunetto Latini, the simoniacal popes, Ulysses, and Ugolino della Gherardesca impose themselves upon the reader’s imagination with tremendous force.\n" +
                "The visit to Hell is, as Virgil and later Beatrice explain, an extreme measure, a painful but necessary act before real recovery can begin. This explains why the Inferno is both aesthetically and theologically incomplete. For instance, readers frequently express disappointment at the lack of dramatic or emotional power in the final encounter with Satan in canto XXXIV. But because the journey through the Inferno primarily signifies a process of separation and thus is only the initial step in a fuller development, it must end with a distinct anticlimax. In a way this is inevitable because the final revelation of Satan can have nothing new to offer: the sad effects of his presence in human history have already become apparent throughout the Inferno.\n" +
                "In the Purgatorio the protagonist’s painful process of spiritual rehabilitation commences; in fact, this part of the journey may be considered the poem’s true moral starting point. Here the pilgrim Dante subdues his own personality in order that he may ascend. In fact, in contrast to the Inferno, where Dante is confronted with a system of models that needs to be discarded, in the Purgatorio few characters present themselves as models; all of the penitents are pilgrims along the road of life. Dante, rather than being an awed if alienated observer, is an active participant. If the Inferno is a canticle of enforced and involuntary alienation, in which Dante learns how harmful were his former allegiances, in the Purgatorio he comes to accept as most fitting the essential Christian image of life as a pilgrimage. As Beatrice in her magisterial return in the earthly paradise reminds Dante, he must learn to reject the deceptive promises of the temporal world.\n" +
                "Despite its harsh regime, the Purgatorio is the realm of spiritual dawn, where larger visions are entertained. Whereas in only one canto of the Inferno (VII), in which Fortuna is discussed, is there any suggestion of philosophy, in the Purgatorio, historical, political, and moral vistas are opened up. It is, moreover, the great canticle of poetry and the arts. Dante meant it literally when he proclaimed, after the dreary dimensions of Hell: “But here let poetry rise again from the dead.” There is only one poet in Hell proper and not more than two in the Paradiso, but in the Purgatorio the reader encounters the musicians Casella and Belacqua and the poet Sordello and hears of the fortunes of the two Guidos, Guinizelli and Cavalcanti, the painters Cimabue and Giotto, and the miniaturists. In the upper reaches of Purgatory, the reader observes Dante reconstructing his classical tradition and then comes even closer to Dante’s own great native tradition (placed higher than the classical tradition) when he meets Forese Donati, hears explained—in an encounter with Bonagiunta da Lucca—the true resources of the dolce stil nuovo, and meets with Guido Guinizelli and hears how he surpassed in skill and poetic mastery the reigning regional poet, Guittone d’Arezzo. These cantos resume the line of thought presented in the Inferno (IV), where among the virtuous pagans Dante announces his own program for an epic and takes his place, “sixth among that number,” alongside the classical writers. In the Purgatorio he extends that tradition to include Statius (whose Thebaid did in fact provide the matter for the more grisly features of the lower inferno), but he also shows his more modern tradition originating in Guinizelli. Shortly after his encounter with Guinizelli comes the long-awaited reunion with Beatrice in the earthly paradise. Thus, from the classics Dante seems to have derived his moral and political understanding as well as his conception of the epic poem—that is, a framing story large enough to encompass the most important issues of his day, but it was from his native tradition that he acquired the philosophy of love that forms the Christian matter of his poem.\n" +
                "This means of course that Virgil, Dante’s guide, must give way to other leaders, and in a canticle generally devoid of drama the rejection of Virgil becomes the single dramatic event. Dante’s use of Virgil is one of the richest cultural appropriations in literature. To begin, in Dante’s poem he is an exponent of classical reason. He is also a historical figure and is presented as such in the Inferno (I): “…once I was a man, and my parents were Lombards, both Mantuan by birth. I was born sub Julio, though late in his time, and I lived in Rome under the good Augustus, in the time of the false and lying gods.” Virgil, moreover, is associated with Dante’s homeland (his references are to contemporary Italian places), and his background is entirely imperial. (Born under Julius Caesar, he extolled Augustus Caesar.) He is presented as a poet, the theme of whose great epic sounds remarkably similar to that of Dante’s poem: “I was a poet and sang of that just son of Anchises who came from Troy after proud Ilium was burned.” So, too, Dante sings of the just son of a city, Florence, who was unjustly expelled, and forced to search, as Aeneas had done, for a better city, in his case the heavenly city.\n" +
                "Virgil is a poet whom Dante had studied carefully and from whom he had acquired his poetic style, the beauty of which has brought him much honour. But Dante had lost touch with Virgil in the intervening years, and when the spirit of Virgil returns it is one that seems weak from long silence. But the Virgil that returns is more than a stylist; he is the poet of the Roman Empire, a subject of great importance to Dante, and he is a poet who has become a saggio, a sage, or moral teacher.\n" +
                "Though an exponent of reason, Virgil has become an emissary of divine grace, and his return is part of the revival of those simpler faiths associated with Dante’s earlier trust in Beatrice. And yet, of course, Virgil by himself is insufficient. It cannot be said that Dante rejects Virgil; rather, he sadly found that nowhere in Virgil’s work—that is, in his consciousness—was there any sense of personal liberation from the enthrallment of history and its processes. Virgil had provided Dante with moral instruction in survival as an exile, which is the theme of his own poem as well as Dante’s, but he clung to his faith in the processes of history, which, given their culmination in the Roman Empire, were deeply consoling. Dante, on the other hand, was determined to go beyond history because it had become for him a nightmare.\n" +
                "In the Paradiso true heroic fulfillment is achieved. Dante’s poem gives expression to those figures from the past who seem to defy death. Their historical impact continues and the totality of their commitment inspires in their followers a feeling of exaltation and a desire for identification. In his encounters with such characters as his great-great-grandfather Cacciaguida and Saints Francis, Dominic, and Bernard, Dante is carried beyond himself. The Paradiso is consequently a poem of fulfillment and of completion. It is the fulfillment of what is prefigured in the earlier canticles. Aesthetically it completes the poem’s elaborate system of anticipation and retrospection."));

        bookDetails.add(new BookDetails("Things Fall Apart", "Things Fall Apart, first novel by Chinua Achebe, written in English and published in 1958. Things Fall Apart helped create the Nigerian literary renaissance of the 1960s.\n" +
                "ZUMAPRESS.com— Keystone Pictures/age fotostock\n" +
                "Afar. Ethiopia. Cattle move towards Lake Abhebad in Afar, Ethiopia.\n" +
                "BRITANNICA QUIZ\n" +
                "Destination Africa: Fact or Fiction?\n" +
                "All countries with Guinea in their names are in Africa.\n" +
                "The novel chronicles the life of Okonkwo, the leader of an Igbo community, from the events leading up to his banishment from the community for accidentally killing a clansman, through the seven years of his exile, to his return, and it addresses a particular problem of emergent Africa—the intrusion in the 1890s of white missionaries and colonial government into tribal Igbo society. Traditionally structured, and peppered with Igbo proverbs, it describes the simultaneous disintegration of its protagonist Okonkwo and of his village. The novel was praised for its intelligent and realistic treatment of tribal beliefs and of psychological disintegration coincident with social unraveling."));
        bookDetails.add(new BookDetails("Fairy tales", "     Cinderella - Her evil stepmother and stepsisters would not let her go to the ball, but her fairy godmother made it happen with magic. She danced with the prince and they fell in love. Since she had to leave by midnight, she ran and lost one slipper. The prince found the slipper and searched for her. After he found her, they were married and lived happily ever after.\n" +
                "\n" +
                "Elves and the Shoemaker - A shoemaker and his wife were very poor. One day they ran out of leather so they went to bed. In the morning, they found a pair of shoes and a passerby bought them. The next night, another pair of shoes appeared. The third night they hid and saw two elves making shoes. In gratitude, they made clothes for the elves, as winter was approaching. The elves were very happy and went on to help someone else.\n" +
                "\n" +
                "Emperor's New Clothes - A vain emperor hired two people to make him some new clothes. The tricked him, telling him the cloth was not visible to people unfit for his position or who were very stupid. At first the people pretended to see the clothes, but a child says that he is not wearing clothes and people start to agree. The emperor realized he was swindled but continues the parade anyway.\n" +
                "\n" +
                "Frog-Prince - A frog asked a princess why she was crying and she replied that she had dropped her golden ball into the pond. She promised anything if he would get it for her. He did and asked to eat from her plate, live in the castle, and that she be his friend. She did and he turned into a prince as he had been under a spell from a witch. They married and lived happily ever after.\n" +
                "\n" +
                "The Gingerbread Man - A little old woman baked a gingerbread man and when she took him out of the oven, he ran away. The woman and her husband chased him, as well as the pig, cow and horse. No one could catch him. He came to a river and a sly fox told him he could jump on his tail and he would take him across. He did and the fox went deeper and the gingerbread man had to jump on his back and then on his nose. When he got to his nose, the fox ate him.\n" +
                "\n" +
                "Goldilocks and the Three Bears - Goldilocks saw a cabin in the woods and entered, she found three bowls of porridge, one was too cold, one too hot and the other just right, so she ate it. She found three chairs, one to hard, one too soft, and the little one was just right and she sat in it and broke it. Of the three beds, one was too hard, one too soft and one just right, so she fell asleep. The bears came home and frightened her and she ran away.\n" +
                "\n" +
                "Hansel and Gretel - The two childrens' wicked stepmother took them into the forest and left them there. They came upon a house made of sweets and they ate some. The evil witch that lived there locked them in a cage and was going to make a soup out of them. Gretel got out of the cage and pushed the witch into the boiling water. The children found treasure there and took it home and they were never hungry again.\n" +
                "\n" +
                "Jack and the Bean Stalk - Jack took the family cow to sell and traded it for magic beans. His mother was angry and threw them out of the window. The next morning a giant beanstalk had grown. He climbed the beanstalk and found a giant there who had gold coins. Jack stole them and took them home. Later, Jack returned and saw a hen that laid golden eggs and he stole that, too. The third time he tried to steal a magic harp and the harp cried out. The giant chased Jack down the beanstalk, Jack chopped it down and the giant died.\n" +
                "\n" +
                "Little Red Riding Hood - Little Red Riding Hood's mother sent her to Grandma's house with a basket of goodies and told her not to talk to strangers. A wolf asked here where she was going and she told him. He went to Grandma's house, locked Grandma in the cupboard and put on her clothes. Little Red Riding Hood was surprised at Grandma's eyes, ears and teeth, remarking on how big they were. The wolf said the teeth were better for eating and he pounced. She screamed, some woodcutters heard her cry and rescued her.\n" +
                "\n" +
                "The Pied Piper of Hamelin - The town of Hamlyn was overrun with rats. The Pied Piper offered to get rid of the rats for 50 pounds and the mayor agreed. He started playing his pipe. The rats followed him and he led them into the harbor and they died. He went back for his money but the mayor only paid 20 pounds. The Pied Piper wanted to teach him a lesson, so he played his pipe and all the children followed him out of town. The mayor sent men to find the children but they could not find them.\n" +
                "\n" +
                "Pinocchio - Gepetto was a poor carpenter who carved a puppet that became live. He named him Pinocchio and sent him to school. One day Pinocchio joined a puppet show but the puppet master wanted him for firewood. He begged to be spared and told him about his poor father. He was spared and the puppet master gave him five gold coins for his father.\n" +
                "\n" +
                "Princess and the Pea - A prince wanted to make sure he married a real princess. He devised a test for an unexpected guest who claimed she was a princess. He placed a pea beneath 20 mattresses and 20 feather beds thinking only a princess could be sensitive enough to feel the small pea. The next morning, hte princess said she did not sleep because of something hard in her bed. The two were married and lived happily everafter.\n" +
                "\n" +
                "Sleeping Beauty - A princess was born and an old fairy placed a spell that she would prick her finger on a spindle when she was 16 and die. The good fairies made another spell so that she would only sleep for 100 years and a prince would awaken her. When she was 16, the witch, disguised as an old lady, showed her a spinning wheel and she touched the spindle and fell asleep. The good fairies decided to make everyone sleep. After 100 years, a prince from another land found her and kissed her. Everyone awoke, they married and lived happily every after.\n" +
                "\n" +
                "Snow White and the Seven Dwarfs - Snow White's evil stepmother wanted to be the fairest in the land and was jealous of Snow White's beauty. The stepmother ordered Snow White to be killed but the huntsman spared her life. Snow White came upon a cottage that belonged to seven dwarfs and they let her stay. Soon the wicked stepmother found her, disguised herself and took her a poison apple. She fell into a deep sleep and the dwarfs made a crystal coffin for her. Prince Charming came by the cottage, saw her, kissed her, and she awoke. They were married and lived happily ever after.\n" +
                "\n" +
                "Three Little Pigs - One pig built a house of straw and the second a house of sticks, because they were lazy. The third took the time to build a strong house with bricks. When the big bad wolf came, he huffed and puffed and blew the straw and stick houses down. He couldn't blow down the brick house and the pigs put a pot of boiling water in the fireplace. The wolf fell into it and died.\n" +
                "\n" +
                "Thumbelina - A woman wished for a baby, even a tiny one. A fairy granted her wish and gave her a seed to plant. When it bloomed, a tiny baby was inside. A toad fell in love with the baby and kidnapped her. A swallow rescued the baby and took her away to warmer lands. There, Thumbelina found another tiny person just like her. He asked her to marry him and she became queen of the flowers.\n" +
                "\n" +
                "Ugly Ducklibong - One duckling did not look like the others and he was sad. He decided to run away and came across a cottage. He stayed there for a while but the children scared him. He left and spent the winter in the pond. In the spring, he saw his reflection and realized he was a swan."));
        bookDetails.add(new BookDetails("The Divine Comedy", "Dante’s years of exile were years of difficult peregrinations from one place to another—as he himself repeatedly says, most effectively in Paradiso [XVII], in Cacciaguida’s moving lamentation that “bitter is the taste of another man’s bread and…heavy the way up and down another man’s stair.” Throughout his exile Dante nevertheless was sustained by work on his great poem. The Divine Comedy was possibly begun prior to 1308 and completed just before his death in 1321, but the exact dates are uncertain. In addition, in his final years Dante was received honourably in many noble houses in the north of Italy, most notably by Guido Novello da Polenta, the nephew of the remarkable Francesca, in Ravenna. There at his death Dante was given an honourable burial attended by the leading men of letters of the time, and the funeral oration was delivered by Guido himself.\n" +
                "Gabriele D'Annunzio.\n" +
                "READ MORE ON THIS TOPIC\n" +
                "Italian literature: Dante (1265–1321)\n" +
                "Dante Alighieri is one of the most important and influential names in all of European literature, but it was only after...\n" +
                "The plot of The Divine Comedy is simple: a man, generally assumed to be Dante himself, is miraculously enabled to undertake an ultramundane journey, which leads him to visit the souls in Hell, Purgatory, and Paradise. He has two guides: Virgil, who leads him through the Inferno and Purgatorio, and Beatrice, who introduces him to Paradiso. Through these fictional encounters taking place from Good Friday evening in 1300 through Easter Sunday and slightly beyond, Dante learns of the exile that is awaiting him (which had, of course, already occurred at the time of the writing). This device allowed Dante not only to create a story out of his pending exile but also to explain the means by which he came to cope with his personal calamity and to offer suggestions for the resolution of Italy’s troubles as well. Thus, the exile of an individual becomes a microcosm of the problems of a country, and it also becomes representative of the fall of humankind. Dante’s story is thus historically specific as well as paradigmatic.\n" +
                "Dante and Virgil beset by demons, passing through Hell, illustration by Gustave Doré for an 1861 edition of Dante's Inferno (The Divine Comedy).\n" +
                "© Photos.com/Thinkstock\n" +
                "The basic structural component of The Divine Comedy is the canto. The poem consists of 100 cantos, which are grouped together into three sections, or canticles, Inferno, Purgatorio, and Paradiso. Technically there are 33 cantos in each canticle and one additional canto, contained in the Inferno, which serves as an introduction to the entire poem. For the most part the cantos range from about 136 to about 151 lines. The poem’s rhyme scheme is the terza rima (aba, bcb, cdc, etc.). Thus, the divine number of three is present in every part of the work.\n" +
                "Dante’s Inferno differs from its great classical predecessors in both position and purpose. In Homer’s Odyssey (Book XII) and Virgil’s Aeneid (Book VI) the visit to the land of the dead occurs in the middle of the poem because in these centrally placed books the essential values of life are revealed. Dante, while adopting the convention, transforms the practice by beginning his journey with the visit to the land of the dead. He does this because his poem’s spiritual pattern is not classical but Christian: Dante’s journey to Hell represents the spiritual act of dying to the world, and hence it coincides with the season of Christ’s own death. (In this way, Dante’s method is similar to that of Milton in Paradise Lost, where the flamboyant but defective Lucifer and his fallen angels are presented first.) The Inferno represents a false start during which Dante, the character, must be disabused of harmful values that somehow prevent him from rising above his fallen world. Despite the regressive nature of the Inferno, Dante’s meetings with the roster of the damned are among the most memorable moments of the poem: the Neutrals, the virtuous pagans, Francesca da Rimini, Filipo Argenti, Farinata degli Uberti, Piero delle Vigne, Brunetto Latini, the simoniacal popes, Ulysses, and Ugolino della Gherardesca impose themselves upon the reader’s imagination with tremendous force.\n" +
                "The visit to Hell is, as Virgil and later Beatrice explain, an extreme measure, a painful but necessary act before real recovery can begin. This explains why the Inferno is both aesthetically and theologically incomplete. For instance, readers frequently express disappointment at the lack of dramatic or emotional power in the final encounter with Satan in canto XXXIV. But because the journey through the Inferno primarily signifies a process of separation and thus is only the initial step in a fuller development, it must end with a distinct anticlimax. In a way this is inevitable because the final revelation of Satan can have nothing new to offer: the sad effects of his presence in human history have already become apparent throughout the Inferno.\n" +
                "In the Purgatorio the protagonist’s painful process of spiritual rehabilitation commences; in fact, this part of the journey may be considered the poem’s true moral starting point. Here the pilgrim Dante subdues his own personality in order that he may ascend. In fact, in contrast to the Inferno, where Dante is confronted with a system of models that needs to be discarded, in the Purgatorio few characters present themselves as models; all of the penitents are pilgrims along the road of life. Dante, rather than being an awed if alienated observer, is an active participant. If the Inferno is a canticle of enforced and involuntary alienation, in which Dante learns how harmful were his former allegiances, in the Purgatorio he comes to accept as most fitting the essential Christian image of life as a pilgrimage. As Beatrice in her magisterial return in the earthly paradise reminds Dante, he must learn to reject the deceptive promises of the temporal world.\n" +
                "Despite its harsh regime, the Purgatorio is the realm of spiritual dawn, where larger visions are entertained. Whereas in only one canto of the Inferno (VII), in which Fortuna is discussed, is there any suggestion of philosophy, in the Purgatorio, historical, political, and moral vistas are opened up. It is, moreover, the great canticle of poetry and the arts. Dante meant it literally when he proclaimed, after the dreary dimensions of Hell: “But here let poetry rise again from the dead.” There is only one poet in Hell proper and not more than two in the Paradiso, but in the Purgatorio the reader encounters the musicians Casella and Belacqua and the poet Sordello and hears of the fortunes of the two Guidos, Guinizelli and Cavalcanti, the painters Cimabue and Giotto, and the miniaturists. In the upper reaches of Purgatory, the reader observes Dante reconstructing his classical tradition and then comes even closer to Dante’s own great native tradition (placed higher than the classical tradition) when he meets Forese Donati, hears explained—in an encounter with Bonagiunta da Lucca—the true resources of the dolce stil nuovo, and meets with Guido Guinizelli and hears how he surpassed in skill and poetic mastery the reigning regional poet, Guittone d’Arezzo. These cantos resume the line of thought presented in the Inferno (IV), where among the virtuous pagans Dante announces his own program for an epic and takes his place, “sixth among that number,” alongside the classical writers. In the Purgatorio he extends that tradition to include Statius (whose Thebaid did in fact provide the matter for the more grisly features of the lower inferno), but he also shows his more modern tradition originating in Guinizelli. Shortly after his encounter with Guinizelli comes the long-awaited reunion with Beatrice in the earthly paradise. Thus, from the classics Dante seems to have derived his moral and political understanding as well as his conception of the epic poem—that is, a framing story large enough to encompass the most important issues of his day, but it was from his native tradition that he acquired the philosophy of love that forms the Christian matter of his poem.\n" +
                "This means of course that Virgil, Dante’s guide, must give way to other leaders, and in a canticle generally devoid of drama the rejection of Virgil becomes the single dramatic event. Dante’s use of Virgil is one of the richest cultural appropriations in literature. To begin, in Dante’s poem he is an exponent of classical reason. He is also a historical figure and is presented as such in the Inferno (I): “…once I was a man, and my parents were Lombards, both Mantuan by birth. I was born sub Julio, though late in his time, and I lived in Rome under the good Augustus, in the time of the false and lying gods.” Virgil, moreover, is associated with Dante’s homeland (his references are to contemporary Italian places), and his background is entirely imperial. (Born under Julius Caesar, he extolled Augustus Caesar.) He is presented as a poet, the theme of whose great epic sounds remarkably similar to that of Dante’s poem: “I was a poet and sang of that just son of Anchises who came from Troy after proud Ilium was burned.” So, too, Dante sings of the just son of a city, Florence, who was unjustly expelled, and forced to search, as Aeneas had done, for a better city, in his case the heavenly city.\n" +
                "Virgil is a poet whom Dante had studied carefully and from whom he had acquired his poetic style, the beauty of which has brought him much honour. But Dante had lost touch with Virgil in the intervening years, and when the spirit of Virgil returns it is one that seems weak from long silence. But the Virgil that returns is more than a stylist; he is the poet of the Roman Empire, a subject of great importance to Dante, and he is a poet who has become a saggio, a sage, or moral teacher.\n" +
                "Though an exponent of reason, Virgil has become an emissary of divine grace, and his return is part of the revival of those simpler faiths associated with Dante’s earlier trust in Beatrice. And yet, of course, Virgil by himself is insufficient. It cannot be said that Dante rejects Virgil; rather, he sadly found that nowhere in Virgil’s work—that is, in his consciousness—was there any sense of personal liberation from the enthrallment of history and its processes. Virgil had provided Dante with moral instruction in survival as an exile, which is the theme of his own poem as well as Dante’s, but he clung to his faith in the processes of history, which, given their culmination in the Roman Empire, were deeply consoling. Dante, on the other hand, was determined to go beyond history because it had become for him a nightmare.\n" +
                "In the Paradiso true heroic fulfillment is achieved. Dante’s poem gives expression to those figures from the past who seem to defy death. Their historical impact continues and the totality of their commitment inspires in their followers a feeling of exaltation and a desire for identification. In his encounters with such characters as his great-great-grandfather Cacciaguida and Saints Francis, Dominic, and Bernard, Dante is carried beyond himself. The Paradiso is consequently a poem of fulfillment and of completion. It is the fulfillment of what is prefigured in the earlier canticles. Aesthetically it completes the poem’s elaborate system of anticipation and retrospection."));

        return bookDetails;
    }
}
